SELECT USER
FROM DUAL;


SELECT USER
FROM DUAL;


--○ 기존 테이블 제거
DROP TABLE TBL_SCORE PURGE;
--==>> Table TBL_SCORE이(가) 삭제되었습니다.





--○ 리스트 조회 쿼리문 구성
--  (번호, 이름, 국어점수, 영어점수, 수학점수, 총점, 평균)
SELECT SID, NAME, KOR, ENG, MAT
     , (KOR+ENG+MAT) AS TOT
     , (KOR+ENG+MAT)/3 AS AVG
FROM TBL_SCORE
ORDER BY SID;
--> 한줄 구성
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, (KOR+ENG+MAT)/3 AS AVG FROM TBL_SCORE ORDER BY SID
;

--○ 데이터 입력 쿼리문 구성
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT)
VALUES(SCORESEQ.NEXTVAL, '박현수', 90,80,70 );
-- 한줄 구성
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '박현수', 90,80,70 )
;
--==>> 1 행 이(가) 삽입되었습니다.

INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '임소민', 80,70,60 )
;
--==>> 1 행 이(가) 삽입되었습니다.

INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '우수정', 70,60,50 )
;
--==>> 1 행 이(가) 삽입되었습니다.

--○ 확인
SELECT*
FROM TBL_SCORE;
/*
1	박현수	90	80	70
2	임소민	80	70	60
3	우수정	70	60	50
*/

--○ 커밋
COMMIT;
--==>> 커밋 완료.

SELECT COUNT(*) AS COUNT FROM TBL_SCORE
;

